### ISSUE TITLE
problem when used in fragment

### ISSUE THREAD

**Issue by kia1349** [codekidX/storage-chooser#111]
I encounter this error when i use it in an androidx fragment

'withFragmentManager(android.app.FragmentManager)' in 'com.codekidlabs.storagechooser.StorageChooser.Builder' cannot be applied to '(androidx.fragment.app.FragmentManager)'

![Untitled](https://user-images.githubusercontent.com/10990724/64314514-767db400-cfc4-11e9-81d7-2f84f1eb2433.png)

**Comment by codekidX** [comment]
Did you follow all the steps written [here](https://github.com/codekidX/storage-chooser#installation)? Especially the last part?

The world of Android is moving towards `androidx` and I wouldn't want this library to support legacy `FragmentManager`. I'd suggest you to [Move to AndroidX](https://developer.android.com/jetpack/androidx/migrate) as well.

**Comment by kia1349** [comment]
Thank you. Yes. I've moved my project to Android X
getSupportFragmentManager() used when you are in activity and want to get a fragment but i am in the fragment
i can use   FragmentManager fragManager = getActivity().getSupportFragmentManager();  in my fragment
but   .withFragmentManager refered to your StorageChooser class  line:219 and it use android.app.FragmentManager as parameter again

**Comment by kia1349** [comment]
i solved by this maner in fragment:

        builder.withActivity(getActivity())
                .withFragmentManager(getActivity().getFragmentManager())
                .setMemoryBarHeight(1.5f)
                .withContent(c);



thanks again and i am waiting for new version

**Comment by codekidX** [comment]
Oh, ya the `supportFragmentManager` is the `getActivity().getFragmentManager()` in androidx, my bad. Glad that it solved your issue, closing this one.
