### ISSUE TITLE
Predefined Path not work?

### ISSUE THREAD

**Issue by Vraha** [codekidX/storage-chooser#118]
Hello, I have tried putting a predefined path when building for the storage chooser to open at my defined path, but it didn't seem to work, or am I doing it wrong? It should be the .withPredefinedPath(STATIC_PATH) method right?

**Comment by Vraha** [comment]
let's say I would like the storage chooser to open from TEST folder within my internal storage, is it the correct way to do it?

chooser = new StorageChooser.Builder()
                .withActivity(MainActivity.this)
                .withFragmentManager(getFragmentManager())
                .withMemoryBar(true)
                .allowCustomPath(true)
                .allowAddFolder(true)
                .disableMultiSelect()
                .setType(StorageChooser.FILE_PICKER)
                **.withPredefinedPath(/storage/emulated/0/TEST)**
                .build();

However, it didn't seem to work. Thanks in advance

**Comment by innerman** [comment]
@Vraha:
.withPredefinedPath did not work for me either. What worked was this:

StorageChooser.Builder builder = new StorageChooser.Builder();
builder.withActivity(MainActivity.this)
                .withFragmentManager(getFragmentManager())
                .withMemoryBar(true)
                .allowCustomPath(true)
                .customFilter(allowedExtensions)
                .disableMultiSelect()
                .withContent(c)
                .skipOverview(true, "/storage/emulated/0/TEST")
                .setType(StorageChooser.FILE_PICKER);
chooser = builder.build();
chooser.show();

**Comment by Vraha** [comment]
@innerman thanks mate! works like a charm
