### ISSUE TITLE
How do I enable folder creation?

### ISSUE THREAD

**Issue by rahulpopuri** [codekidX/storage-chooser#12]
I'm following the readme to build a directory chooser, but I seem to be missing the "+" from the screenshots to create folders - how do I enable that ?

> StorageChooser chooser = new StorageChooser.Builder()
                .withActivity(this.getActivity())
                .withFragmentManager(this.getFragmentManager())
                .withMemoryBar(true)
                .allowCustomPath(true)
                .setType(StorageChooser.DIRECTORY_CHOOSER)
                .build();

**Comment by codekidX** [comment]
You just have to add `.allowAddFolder(true)` to your builder. A detailed documentation of all other methods will be available today I'll link it to this issue tracker for your reference. 😄

**Comment by rahulpopuri** [comment]
Thank you! It took me literally 5 mins to add this directory chooser to my app. Great work

**Comment by codekidX** [comment]
[Javadoc](https://jitpack.io/com/github/codekidX/storage-chooser/21c545f/javadoc/) for your reference.
