### ISSUE TITLE
Now Android.app.fragmentmanager is deprecated

### ISSUE THREAD

**Issue by broteam168** [codekidX/storage-chooser#122]
I have use this lib but my program now use support.v4.app lib so i can't convert to.Anyone have any solution.
p/s:i have open source code and add android.support.v4.app replace android.app but spmething go wrong

**Comment by codekidX** [comment]
Hello @broteam168, I'm aware that it is deprecated and `androidx.fragment.app.FragmentManager` is being supported in the upcoming 3.0 version which is developed in `inline-3.0` branch.

I think it's a really simple migration that can be done to `2.x` version of this library but I'm occupied with `3.0` development and some other projects most of the time. You can submit a PR to master branch if possible which will be much faster than me working on `2.x` again.

The files that may need changes are _(on-top of the head)_:
1. [StorageChooser.java#withFragmentManager](https://github.com/codekidX/storage-chooser/blob/master/storagechooser/src/main/java/com/codekidlabs/storagechooser/StorageChooser.java)
2. [ChooserDialogFragment](https://github.com/codekidX/storage-chooser/blob/master/storagechooser/src/main/java/com/codekidlabs/storagechooser/fragments/ChooserDialogFragment.java) and [SecondaryChooserFragment](https://github.com/codekidX/storage-chooser/blob/master/storagechooser/src/main/java/com/codekidlabs/storagechooser/fragments/SecondaryChooserFragment.java) have to extend AndroidX's DialogFragment class.

**Comment by broteam168** [comment]
Oh thank for your reply but when i implement in your project it seem to be not found.
