### ISSUE TITLE
Theming the dialog?

### ISSUE THREAD

**Issue by creativetrendsapps** [codekidX/storage-chooser#13]
For some reason the dialog is not following my apps theme. Is there a special way to theme the dialog?
<img src="https://cloud.githubusercontent.com/assets/14278089/23464152/eb5db5b8-fe61-11e6-9f0e-7a5406cc77f2.png" width="22%" height=""> <img src="https://cloud.githubusercontent.com/assets/14278089/23464156/eef34800-fe61-11e6-8f03-dc9632c24d57.png" width="22%" height="">

**Comment by codekidX** [comment]
Make sure that your `colorPrimary` color is overriding the library's color. May be you have colorPrimary set for only `values-v21/colors.xml` not `values/colors.xml`, used by the dialog [here](https://github.com/codekidX/storage-chooser/blob/master/storagechooser/src/main/res/values/colors.xml#L3-L4)

**Comment by codekidX** [comment]
Closing the issue until next encounter of the issue.
