### ISSUE TITLE
There is a while header in 5.0

### ISSUE THREAD

**Issue by skyhacker2** [codekidX/storage-chooser#16]
![s70310-13463026](https://cloud.githubusercontent.com/assets/1547841/23783622/e056bbdc-0597-11e7-8c44-d7c26e869112.jpg)

**Comment by codekidX** [comment]
Interesting, do you get same dialog with this white header in different devices as well ?

**Comment by TheAndroidMaster** [comment]
I have it as well. It's just the title bar (but without a title in it). Will remove it in the next PR.

**Comment by TheAndroidMaster** [comment]
Should be fixed in #20 :)

**Comment by skyhacker2** [comment]
@TheAndroidMaster Nice work
