### ISSUE TITLE
Why only support v4 Fragment?

### ISSUE THREAD

**Issue by xuzc** [codekidX/storage-chooser#17]
Why only support v4 Fragment? 😥

**Comment by codekidX** [comment]
The dialog is inflated with `android.support.v4.app.DialogFragment` so fragment manager of support library is needed. What does your parent activity extend ?

**Comment by mveroukis** [comment]
I'm trying to get this to run on a PreferenceActivity based activity, which does not extend FragmentActivity. From what I can tell, that means I can't use this,

**Comment by codekidX** [comment]
Hi @mveroukis , I'm aware of this drawback presented by using FragmentManager from support library, I'm working on re-routing the dialog through a dummy Activity extending AppCompatActivity. It seems to be the only way. :disappointed:
