### ISSUE TITLE
add .withThreshold(int size, String suffix)

### ISSUE THREAD

**Issue by Kolyall** [codekidX/storage-chooser#18]
What's mean error on log?
```
StorageChooser: add .withThreshold(int size, String suffix) to your StorageChooser.Builder instance
```

**Comment by Kolyall** [comment]
How to use it?

**Comment by codekidX** [comment]
That was a tiny bug which is fixed here - [commit](https://github.com/codekidX/storage-chooser/commit/c38c19f7a0b177b940e69db6f3a8063b5cfb0e3d)

but if you want to know what it does - [commit description](https://github.com/codekidX/storage-chooser/commit/d97c52b915a43fd1220fa1c9036688011c7c32fd)

**Comment by Kolyall** [comment]
Thx, I found the issue, please update readme to new ver for compile))
