### ISSUE TITLE
Backport New Folder Icon Animation to API 16 (and below...)

### ISSUE THREAD

**Issue by fennifith** [codekidX/storage-chooser#23]
Vector Animations are only useful if you're actually changing the shape of the vector drawable's path (such as a morph animation or a visibility strike). Using a regular drawable animation could fix this, or we could be super lazy and rotate the ImageView 45 degrees programatically instead ;)

**Comment by codekidX** [comment]
Haha I thought of the same thing just a while ago, I think I'll add it as enhancement and to the TO-DO list now, although it's not much work. Also I would prefer animating from resource rather than drawable animation, keeps the library light.
