### ISSUE TITLE
How to set file extension for Type(StorageChooser.FILE_PICKER)?

### ISSUE THREAD

**Issue by Kolyall** [codekidX/storage-chooser#25]
How to set file extension for Type(StorageChooser.FILE_PICKER)?
For example I want to select only *.mp3 files, how to do it?

**Comment by codekidX** [comment]
@Kolyall Currently there is no filtering of files implemented in this library, but it's under development and will be added in the upcoming release. 😄 I'm marking this as an enhancement to make sure I finish this as quickly as possible.

**Comment by Kolyall** [comment]
@codekidX thanks, your lib is awesome

**Comment by sgimp** [comment]
yea it would be nice to have that feature. :)

**Comment by codekidX** [comment]
#42
