### ISSUE TITLE
Not able to select subfolders

### ISSUE THREAD

**Issue by kulvinder18may** [codekidX/storage-chooser#27]
I'm able to see single dialog where internal memory or external memory option showing. when i clicked on anyone, dialog dismiss.
i tried with chossertype filepicker as well as directory picker

**Comment by codekidX** [comment]
@kulvinder18may did you also add `.allowCustomPath(true)` to the builder ?

**Comment by kulvinder18may** [comment]
yes also tried with true as well as with false...but not working

**Comment by codekidX** [comment]
- can you share only the snippet of the storage-chooser code ?
- also can you share which version of the library you are using ?
- did you try running the demo app ?

**Comment by kulvinder18may** [comment]
ohh,
yes i checked demo working perfect
it was my implementation mistake, storage permission related

Thanks @codekidX  for your valuable time
