### ISSUE TITLE
Add posibility to choose more than one file

### ISSUE THREAD

**Issue by Kolyall** [codekidX/storage-chooser#28]
Add a list with checkbox to choose more than one file from storage. Thanks
![screenshot24](https://cloud.githubusercontent.com/assets/3495165/24766274/ff6eedfa-1afa-11e7-8060-8152098a15c7.png)

**Comment by codekidX** [comment]
Thanks for the suggestion. I'll add this in 2.1 release. Currently running low on time 😄

**Comment by Kolyall** [comment]
@codekidX did you do something for 2.1?

**Comment by codekidX** [comment]
Hi @Kolyall , currently bouncing back and forth with jobs, I haven't got much time to code this library. This weekend I'll post a barebone version of multiple file selection I'll post here as soon as it's done. Thanks for waiting.

**Comment by codekidX** [comment]
c83228a640bf60e8e8c333aa1056d0965ad2c6bb

Added support to choose multiple files. Let me know if any bug pops up.
