### ISSUE TITLE
Gradle : Failed to resolve

### ISSUE THREAD

**Issue by serkandaglioglu** [codekidX/storage-chooser#29]
I added below to app level gradle and it throws error after sync gradle.

`compile 'com.github.codekidX:storage-chooser:1.0.33'`

Error:(71, 13) Failed to resolve: com.github.codekidX:storage-chooser:1.0.33

**Comment by jackkum** [comment]
I have a same trouble. 
@serkandaglioglu Do you resolve it?

**Comment by codekidX** [comment]
@jackkum It's mostly because you didn't add this - `maven { url "https://jitpack.io" }` to your root build.gradle in repositories.

**Comment by serkandaglioglu** [comment]
@codekidX my problem was same.

**Comment by jackkum** [comment]
@codekidX @serkandaglioglu 
Yes, that is the solution of my problem.
Thanks a lot!
