### ISSUE TITLE
not all config optoins applied

### ISSUE THREAD

**Issue by boomsya** [codekidX/storage-chooser#32]
file: ChooserDialogFragment.java need changes:

```
private View getLayout(LayoutInflater inflater, ViewGroup container) {
private View getLayout(LayoutInflater inflater, ViewGroup container) {
		mConfig = StorageChooser.getsConfig();
		mLayout = inflater.inflate(R.layout.storage_list, container, false);
		initListView(getContext(), mLayout, mConfig.isShowMemoryBar());

		if (mConfig.getDialogTitle() != null) {
			TextView dialogTitle = (TextView) mLayout.findViewById(R.id.dialog_title);
			dialogTitle.setText(mConfig.getDialogTitle());
		}

		return mLayout;
	}
...
// just add the internal storage and avoid adding emulated henceforth
if (mConfig.getInternalStorageText() != null) {
			storages.setStorageTitle(mConfig.getInternalStorageText());
		} else {
			storages.setStorageTitle(INTERNAL_STORAGE_TITLE);
		}

```

**Comment by codekidX** [comment]
Hello, can you tell me which configs are not applied? I re-checked it but couldn't find any issues 😃

**Comment by boomsya** [comment]
private void populateList() {...

YOUR CODE:
// just add the internal storage and avoid adding emulated henceforth
        storages.setStorageTitle(mContent.getInternalStorageText());

MY CODE:
// just add the internal storage and avoid adding emulated henceforth
		if (mConfig.getInternalStorageText() != null) {
			storages.setStorageTitle(mConfig.getInternalStorageText());
		} else {
			storages.setStorageTitle(INTERNAL_STORAGE_TITLE);
		}

**Comment by boomsya** [comment]
and source (SecondaryChooserFragment) have hard-coded constants:

public static String LABEL_SELECT = "Select";
public static String LABEL_CREATE = "Create";
......
// set label of buttons [localization]
mSelectButton.setText(StorageChooserView.LABEL_SELECT);
mCreateButton.setText(StorageChooserView.LABEL_CREATE);

**Comment by codekidX** [comment]
Hi, I think you are viewing older source of the library. It's already moved to Content class. You might want to look at these 3 commits.
[74fe865](https://github.com/codekidX/storage-chooser/commit/74fe865ba205b53f95de64b7624ae84e4f85ae6f)
[5d37c0d](https://github.com/codekidX/storage-chooser/commit/5d37c0dba5d7dc73715ac76162e4addfedfb3763)
[253c36c](uhttps://github.com/codekidX/storage-chooser/commit/253c36c1041cf7a0e5e41068bdc09058a30c95b6rl)

**Comment by ryust** [comment]
That made a mess of things. Do you have a migration guide for removing StorageChooserView?

**Comment by codekidX** [comment]
Hi @ryust, these changes are not public _(in any release)_ yet and if you are using a snapshot or with the latest commit hash you just need to make an instance of Content and set your label and localizing strings and then pass that content instance to the builder. As shown here - https://github.com/codekidX/storage-chooser/commit/253c36c1041cf7a0e5e41068bdc09058a30c95b6.

**Comment by ryust** [comment]
I tried changing StorageChooserView to Content, but none of the methods match up. What is the replacement for StorageChooserView?

**Comment by boomsya** [comment]
super. Thanks.
maybe i will send for you my version of component in ZIP for include in this project?
i have added some good features

**Comment by codekidX** [comment]
@boomsya will you be able to fork this repository and add your changes to that repository? It'll be better for me to sort out without conflicts.

@ryust all the methods are ported from StorageChooserView to Content, with some of the method name changed you can compare 
this - https://github.com/codekidX/storage-chooser/wiki/Localizing-your-Chooser &
this - https://github.com/codekidX/storage-chooser/commit/253c36c1041cf7a0e5e41068bdc09058a30c95b6
to migrate your code to content.
