### ISSUE TITLE
Possibility to change textColor

### ISSUE THREAD

**Issue by sweaf** [codekidX/storage-chooser#34]
Hi,
I am using Theme.AppCompat in my app and the StorageChooser Dialog has white text on white background. I did not find any way to change the text color. Is this possible and if not, it would be a great enhancement.

**Comment by codekidX** [comment]
Hi, color of the text is hardcoded right now so I'll extract a color resource in upcoming commits and also provide a method to change color using the [Content](https://github.com/codekidX/storage-chooser/blob/master/storagechooser/src/main/java/com/codekidlabs/storagechooser/Content.java) class.

Thanks for reporting.
