### ISSUE TITLE
White screen and stuck in ColorOS

### ISSUE THREAD

**Issue by Trumeet** [codekidX/storage-chooser#37]
In the OPPO phone ColorOS above can not click, the dialog box white screen, stuck, can only be forced to stop.
(This is my user feedback, I do not have ColorOS)
![Screenshot](https://ooo.0o0.ooo/2017/06/13/593fbc3104c7b.png)
Hope you try to fix it, thanks

**Comment by codekidX** [comment]
Hey, can you get me an error log ? It's hard to debug with so less information.

**Comment by Trumeet** [comment]
Sorry for a long time did not reply to you.
I wrote a Demo issued to the ColorOS users, it did not even have this problem!
I suspect that the version of my other project may be too low. Thank you for waiting, temporarily closed it.
🤣
