### ISSUE TITLE
While creating a new folder, you can enter line feeds while entering a folder name

### ISSUE THREAD

**Issue by mveroukis** [codekidX/storage-chooser#39]
![image](https://user-images.githubusercontent.com/7936453/27464552-ba094ed8-5793-11e7-816b-984cf64daece.png)

As the screenshot above demonstrates, while entering a folder name in the create box, you can enter multiple line feeds. Hitting the create button results in an error, which I guess is ok, but the user should not be allowed to enter a line feed.

This can be done easily on the soft keyboard by calling setImeOptions(EditorInfo.IME_ACTION_DONE). However, you'll also need to filter out line feeds (and any other funny characters that may not be appropriate for a folder name) using a filter as user may use a real keyboard. And also, maybe set the maxLines to 1 in case someone copies and pastes multiple lines.

**Comment by codekidX** [comment]
Yes, I missed to add singleLine attribute 😞  I'll fix it asap. Thanks for reporting this issue.
