### ISSUE TITLE
Files may appear when choosing folders

### ISSUE THREAD

**Issue by mveroukis** [codekidX/storage-chooser#40]
Under certain conditions, file names appears even though the type is set to StorageChooser.DIRECTORY_CHOOSER. Steps to repro:

1. Open the Storage Chooser with the type set to DIRECTORY_CHOOSER
1. Navigate to a folder where you know other files exist (you won't see them yet)
1. Create a new folder, any name
1. Once the folder is created, you see all the files in that folder.

See the linked video:
[YouTube](https://youtu.be/frbjAmcFFhU)

**Comment by codekidX** [comment]
Yeah it seems `trimPopulate()` also needs to check conditions like DIRECTORY_CHOOSER. I'll fix this in upcoming commit. Thanks for pointing this out !
