### ISSUE TITLE
Use mime types for filters

### ISSUE THREAD

**Issue by ryust** [codekidX/storage-chooser#44]
It would be more flexible to have an API to allow input of a list of mime types for the filter instead of the predefined ones. For example, I just want to filter for '*.txt' files, but with the current implementation that is not possible.

**Comment by codekidX** [comment]
@ryust Idk if its coincidence, I was just adding this enhancement. 😁

**Comment by codekidX** [comment]
Here's the [implementation](https://github.com/codekidX/storage-chooser/blob/master/app/src/main/java/com/codekidlabs/storagechooserdemo/MainActivity.java#L157-L160)

Thanks !

**Comment by codekidX** [comment]
Did you add dependency with latest commit hash ?
`com.github.codekidX:storage-chooser: baaf31b `

**Comment by ryust** [comment]
No, had no idea what artifact should be used nor specifically the API to use.

**Comment by ryust** [comment]
Plus, I was looking for a mime type implementation, not just a file extension.

**Comment by codekidX** [comment]
Hi @ryust , I won't be able to add mime-type filter to this library due to time issues but you can submit a pull request.
