### ISSUE TITLE
Is it possible to make .withFragmentManager() accept the supportFragmentManager?

### ISSUE THREAD

**Issue by Lennoard** [codekidX/storage-chooser#46]
I'm trying to call StorageChooser from a fragment.
If the fragment Class extends **android.support.v4.app.Fragment**, getFragmentManager() will of course return **android.support.v4.app.FragmentManager** and therefore _.withFragmentManager(getFragmentManager())_ will not let me do that as it currently only accepts android.app.FragmentManager as parameter.

Is there another way to do it?

PS. I made the fragment extend android.app.Fragment, it works but whenever I switch to this fragment, the other ones (that use support fragment) are not getting shut down, the same happens in the reverse way. Also, they keep visible, like [this](http://www.digitalinternals.com/android/fragment-replace-still-visible/399/)

**Comment by codekidX** [comment]
Hello, the reason why this library removed support for _**android.support.v4.app.FragmentManager**_ in [b52a9fd](https://github.com/codekidX/storage-chooser/commit/b52a9fd1d220266430b1fb262262402d8f951909) is that **_android.app.FragmentManager_** is accessible throughout the app lifecyle.

In your implementation you need to pass `getActivity().getFragmentManager()` as parameter to it.
