### ISSUE TITLE
Change font face

### ISSUE THREAD

**Issue by MustafaMirzaie** [codekidX/storage-chooser#57]
how can I change the setTypeFace of text?

**Comment by codekidX** [comment]
Hi, the textviews are not exposed yet. I'll follow up on this enhancement as soon as possible.

**Comment by codekidX** [comment]
#58

**Comment by MustafaMirzaie** [comment]
thank you very much
but buttons not have type face.

**Comment by codekidX** [comment]
Ah ! Yes, I'll set the heading typeface as the button typeface in the upcoming commit. Thanks for reminding me.
