### ISSUE TITLE
Extend filter to specify exact file extension e.g ".pdf"

### ISSUE THREAD

**Issue by PaulChege** [codekidX/storage-chooser#66]
Is it possible to extend the type filter so that one can filter by a specific file extension. e.g ".pdf" ?

**Comment by codekidX** [comment]
See this - [MainActivityL157-L160](https://github.com/codekidX/storage-chooser/blob/e12de59c174e7c87dfee786991bb8436213cdf73/app/src/main/java/com/codekidlabs/storagechooserdemo/MainActivity.java#L157-L160)
