### ISSUE TITLE
Custom filter performance

### ISSUE THREAD

**Issue by brarcher** [codekidX/storage-chooser#80]
I've attempted to use the custom filter mechanism using v2.0.3. From reading the description of the feature:

> you might not want the user to go into the folders where there are no songs

my understanding is that the dialog will scan the entire storage folder for matching files, then when complete will display a dialog that only shows files and non-empty folders. The use case for this sounds appealing, however in practice I've seen issues. Namely, the delay in scanning the storage folder can be significant. On my device the difference between opening the dialog without and with the filter is +4 sec. That is, for 4 seconds after issuing the request nothing is displayed. Statistics from Google Play on my application show that some users are encountering ANRs from the file viewer due to long delays. Because of this, I needed to disable the filter.

Is there a middle ground which is possible with the file filter feature? Namely, if a filter is configured all folders will be displayed but the contents of the current folder will be filtered? This will allow only some types of files to be selected but will not incur the long startup impact.

**Comment by codekidX** [comment]
Hi, sorry for this so late reply. A possible workaround is to offload this computation from the main thread and show a async loading in the view this will not cause an ANR. This is being developed in the `dev` branch currently and will be available in the next release.

Once again thanks for this detailed report.

**Comment by codekidX** [comment]
Added async loading of files in the above commit, thanks for the support !

![2018_07_08_11_16_57](https://user-images.githubusercontent.com/3619949/42417183-bcbb4e9a-82a0-11e8-9ff9-27de418471f0.gif)

**Comment by brarcher** [comment]
I took a look at the changes. Thanks!
