### ISSUE TITLE
UniversalFileFilter (ArrayList/List)

### ISSUE THREAD

**Issue by hippott** [codekidX/storage-chooser#90]
After [Accept a List instead of ArrayList for flexibility (fix #87)](https://github.com/codekidX/storage-chooser/commit/65c7fc5c48c2f55bdfb5bb5b62cf7ef27ea23c77), there is an issue with `UniversalFileFilter(mConfig.isCustomFilter(), mConfig.getCustomEnum())` in [SecondaryChooserFragment.java](https://github.com/codekidX/storage-chooser/blob/dev/storagechooser/src/main/java/com/codekidlabs/storagechooser/fragments/SecondaryChooserFragment.java) (`protected Boolean doInBackground(Void... voids)`):

![image](https://user-images.githubusercontent.com/34172598/43656515-f33ed132-9752-11e8-9480-a22b9bfc47d4.png)

```
UniversalFileFilter (boolean, java.util.ArrayList<java.lang.String>) in UniversalFileFilter
cannot be applied to (boolean, java.util.List<java.lang.String>)
```

The issue was resolved by reverting back to `ArrayList` instead of the newly implemented `List` in [Accept a List instead of ArrayList for flexibility (fix #87)](https://github.com/codekidX/storage-chooser/commit/65c7fc5c48c2f55bdfb5bb5b62cf7ef27ea23c77). Can you please solve this, @codekidX?

**Comment by codekidX** [comment]
Thanks for pointing it out. Forgot to commit and push !
