### ISSUE TITLE
Root file chooser

### ISSUE THREAD

**Issue by KYHSGeekCode** [codekidX/storage-chooser#98]
How about supporting root files on rooted devices?

(Supporting `/` directories too)

(https://github.com/KYHSGeekCode/Android-Disassembler/issues/32)

Thank you.

**Comment by codekidX** [comment]
Hi, this feature is already under development for 3.0 in `dev-3.0` branch and will be released by 1st December.

Thanks for the suggestion, if you have any other suggestion please feel free to open an issue here.

**Comment by KYHSGeekCode** [comment]
Trying not to impose any burden, well, when does the 3.0 come out?

**Comment by KYHSGeekCode** [comment]
Hello?! I made it myself: https://github.com/KYHSGeekCode/RootFilePicker , and it is used by  https://github.com/KYHSGeekCode/Android-Disassembler

**Comment by codekidX** [comment]
Great work @KYHSGeekCode. Good that you made it .. I removed support from 3.0.
