### ISSUE TITLE
com.codekidlabs.storagechooser.utils.ResourceUtil

### ISSUE THREAD

**Issue by 1stmetro** [codekidX/storage-chooser#99]
Cant import this release, i get the following error, 

error: cannot find symbol class ResourceUtil

Also this fault also,
 
MemoryUtil.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

**Comment by codekidX** [comment]
Hello, can I know which version you are using ?

The last stable version is 2.0.4.3.

**Comment by 1stmetro** [comment]
I was trying the latest release, the older one i had no issues with it.

**Comment by 1stmetro** [comment]
Also did some modifications on the older release to hide some drives that i didnt need, might be useful if you would me to post the code if i have to reuse in the later release of the code ?

**Comment by codekidX** [comment]
Hi, I just tried the `2.0.4.3` release it didn't give me this error. Can you tell what all are being used by your project in `build.gradle`

Also if the drives are not used by user, it'll be really helpful if you send me a pull request on `dev` branch. The `dev-3.0` uses a very different structure.

**Comment by 1stmetro** [comment]
My build.gradle is packed so hard to say why i have the error, maybe easier if i know what version of gradle you are using

With regards to the code i have added, im trying to locate the code, 

Basically i have added an exclusion which will probably make sense when you see it, basically i have excluded "enc_emulated" from showing as a drive, in theory you could add an array of names not to show using the same code, then its simply a case of passing the array of exclusions 

public class MemoryUtil {

    public static final String SELF_DIR_NAME = "self";
    public static final String EMULATED_DIR_NAME = "emulated";
    public static final String EMULATED_DIR_KNOX = "knox-emulated";
    public static final String EMULATED_ENC = "enc_emulated";
    public static final String SDCARD0_DIR_NAME = "sdcard0";
    public static final String CONTAINER = "container";
    private static final String ERROR = "error";

    public boolean isExternalStoragePresent() {
        return getStorageListSize() != 1;
    }

    /**
     * Returns an the number of the files inside '/storage' directory
     *
     * @return int - number of storages present except the redundant once
     */
    public int getStorageListSize() {
        File storageDir = new File("/storage");
        List<File> volumeList = new ArrayList<>();
        Collections.addAll(volumeList, storageDir.listFiles());
        // segregate the list
        for (int i = 0; i < volumeList.size(); i++) {
            String storageName = volumeList.get(i).getName();
            if (storageName.equals(SELF_DIR_NAME) ||
                    storageName.equals(EMULATED_DIR_KNOX) ||
                    storageName.equals(EMULATED_ENC) ||
                    storageName.equals(SDCARD0_DIR_NAME) ||
                    storageName.equals(CONTAINER)) {
                volumeList.remove(i);
            }
        }

        return volumeList.size();
    }

for (File f : volumeList) {
            if (f.isDirectory()
                    && !f.getName().equals(MemoryUtil.SELF_DIR_NAME)
                    && !f.getName().equals(MemoryUtil.EMULATED_DIR_KNOX)
                    && !f.getName().equals(MemoryUtil.EMULATED_DIR_NAME)
                    && !f.getName().equals(MemoryUtil.EMULATED_ENC)
                    && !f.getName().equals(MemoryUtil.SDCARD0_DIR_NAME)
                    && !f.getName().equals(MemoryUtil.CONTAINER)) {

**Comment by NicodeLee** [comment]
i get the following error.
`xecution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\storage-chooser-2.0.4.3.aar\db8ea8fbbbbe618bf1de7b07864c99e0\res\layout\custom_storage_list.xml:156: error: attribute cb_color (aka com.nicodelee.mdxhelp:cb_color) not found.
  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\storage-chooser-2.0.4.3.aar\db8ea8fbbbbe618bf1de7b07864c99e0\res\layout\custom_storage_list.xml:156: error: attribute cb_pressedRingWidth (aka com.nicodelee.mdxhelp:cb_pressedRingWidth) not found.
  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\storage-chooser-2.0.4.3.aar\db8ea8fbbbbe618bf1de7b07864c99e0\res\layout-v21\custom_storage_list.xml:155: error: attribute cb_color (aka com.nicodelee.mdxhelp:cb_color) not found.
  C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\storage-chooser-2.0.4.3.aar\db8ea8fbbbbe618bf1de7b07864c99e0\res\layout-v21\custom_storage_list.xml:155: error: attribute cb_pressedRingWidth (aka com.nicodelee.mdxhelp:cb_pressedRingWidth) not found.
  error: failed linking file resources.`

**Comment by paulasiimwe** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processArm64DebugResources'.
> Android resource linking failed
  Output:  /Users/paulasiimwe/.gradle/caches/transforms-1/files-1.1/storage-chooser-2.0.4.3.aar/7c585f3a24a5374c2f102daf2caa040a/res/layout/custom_storage_list.xml:156: error: attribute cb_color (aka com.app.package:cb_color) not found.
  /Users/paulasiimwe/.gradle/caches/transforms-1/files-1.1/storage-chooser-2.0.4.3.aar/7c585f3a24a5374c2f102daf2caa040a/res/layout/custom_storage_list.xml:156: error: attribute cb_pressedRingWidth (aka com.app.package:cb_pressedRingWidth) not found.
  /Users/paulasiimwe/.gradle/caches/transforms-1/files-1.1/storage-chooser-2.0.4.3.aar/7c585f3a24a5374c2f102daf2caa040a/res/layout-v21/custom_storage_list.xml:155: error: attribute cb_color (aka com.app.package:cb_color) not found.
  /Users/paulasiimwe/.gradle/caches/transforms-1/files-1.1/storage-chooser-2.0.4.3.aar/7c585f3a24a5374c2f102daf2caa040a/res/layout-v21/custom_storage_list.xml:155: error: attribute cb_pressedRingWidth (aka com.app.package:cb_pressedRingWidth) not found.
  error: failed linking file resources.
```

**Comment by codekidX** [comment]
Please change the version to `2.0.4.4`. This was caused due to a bad merge.
